spring:
  application:
    name: 25-10-14-rabbitmq_advanced

  rabbitmq:
    addresses: amqp://liren:123123@127.0.0.1/lirendada
    listener:
      simple:
        acknowledge-mode: manual        # 消息确认
    publisher-confirm-type: correlated  # 发布确认机制