spring:
  application:
    name: 25_9_22_SpringDataRedis
  data:
    redis:
      port: 6379
      password: 123123
      host: 127.0.0.1
      lettuce:
        pool:
          max-idle: 8
          min-idle: 0
          max-active: 8
          max-wait: 1000ms